import { StyleSheet } from 'react-native';
import { SCREEN_MAX_WIDTH, SCREEN_MIN_WIDTH, colors, fonts } from '@/components/ui';

export const appInk = colors.text;
export const appMuted = colors.textSecondary;
const appPaper = colors.background;
const appCard = colors.surface;
export const appBorder = colors.border;
export const appTint = colors.neutralBg;

const roundedText = {
  fontFamily: fonts.rounded,
};

const displayText = {
  fontFamily: fonts.display,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: appPaper,
  },
  shell: {
    flex: 1,
    width: '100%',
    minWidth: SCREEN_MIN_WIDTH,
    maxWidth: SCREEN_MAX_WIDTH,
    alignSelf: 'center',
    backgroundColor: appPaper,
  },
  topBar: {
    minHeight: 58,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appCard,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonSpacer: {
    width: 42,
    height: 42,
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingBottom: 28,
  },
  progressRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  progressText: {
    ...roundedText,
    width: 42,
    color: appMuted,
    fontSize: 12,
    fontWeight: '900',
  },
  progressTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.surfaceMuted,
    overflow: 'hidden',
  },
  progressFill: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
  intro: {
    marginTop: 30,
    marginBottom: 24,
    gap: 10,
  },
  eyebrow: {
    ...roundedText,
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  title: {
    ...displayText,
    color: appInk,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: '900',
  },
  body: {
    ...roundedText,
    color: appMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  stack: {
    gap: 10,
  },
  featurePanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appCard,
    overflow: 'hidden',
    padding: 16,
    gap: 14,
  },
  heroHeader: {
    minHeight: 138,
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.accentDim,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  owlStage: {
    width: 116,
    height: 116,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.accentDim,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primaryActive,
    shadowOpacity: 0.13,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  heroCopy: {
    flex: 1,
    gap: 5,
  },
  heroTitle: {
    ...displayText,
    color: appInk,
    fontSize: 21,
    lineHeight: 25,
    fontWeight: '900',
  },
  signalStack: {
    gap: 8,
  },
  signalRow: {
    minHeight: 64,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appPaper,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  signalIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.neutralBg,
  },
  signalCopy: {
    flex: 1,
    gap: 2,
  },
  signalTitle: {
    ...roundedText,
    color: appInk,
    fontSize: 13,
    fontWeight: '900',
  },
  signalBody: {
    ...roundedText,
    color: appMuted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  featureTitle: {
    ...displayText,
    color: appInk,
    fontSize: 23,
    lineHeight: 29,
    fontWeight: '900',
  },
  featureBody: {
    ...roundedText,
    color: appMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  option: {
    minHeight: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appCard,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  optionSelected: {
    borderColor: colors.primary,
    backgroundColor: appTint,
  },
  optionCompact: {
    minHeight: 42,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: appBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  optionText: {
    ...roundedText,
    flex: 1,
    color: appInk,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '900',
  },
  recommendedPill: {
    borderRadius: 8,
    backgroundColor: colors.successBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  recommendedText: {
    ...roundedText,
    color: colors.success,
    fontSize: 10,
    fontWeight: '900',
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    minWidth: 148,
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    paddingHorizontal: 14,
    paddingVertical: 13,
    backgroundColor: appCard,
  },
  chipRecommended: {
    borderColor: colors.borderStrong,
  },
  chipSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  chipText: {
    ...roundedText,
    color: appInk,
    fontSize: 13,
    fontWeight: '900',
  },
  chipTextSelected: {
    color: colors.onPrimary,
  },
  notice: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  noticeText: {
    ...roundedText,
    flex: 1,
    color: appInk,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  recommendation: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appCard,
    padding: 16,
    gap: 8,
  },
  recommendTitle: {
    ...roundedText,
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
  },
  recommendText: {
    ...roundedText,
    color: appInk,
    fontSize: 13,
    lineHeight: 19,
  },
  valuePanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.successBg,
    padding: 18,
    gap: 7,
  },
  valueLabel: {
    ...roundedText,
    color: colors.success,
    fontSize: 13,
    fontWeight: '800',
  },
  valueAmount: {
    ...displayText,
    color: appInk,
    fontSize: 33,
    fontWeight: '900',
  },
  valueCaption: {
    ...roundedText,
    color: appMuted,
    fontSize: 11,
  },
  resultPanel: {
    borderRadius: 8,
    backgroundColor: appCard,
    borderWidth: 1,
    borderColor: appBorder,
    padding: 18,
    gap: 12,
  },
  resultEyebrow: {
    ...roundedText,
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
  },
  resultTitle: {
    ...displayText,
    color: appInk,
    fontSize: 28,
    lineHeight: 33,
    fontWeight: '900',
  },
  resultBody: {
    ...roundedText,
    color: appMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  divider: {
    height: 1,
    backgroundColor: appBorder,
  },
  resultAmount: {
    ...displayText,
    color: appInk,
    fontSize: 31,
    fontWeight: '900',
  },
  trustPanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appCard,
    padding: 18,
    gap: 10,
  },
  panelTitle: {
    ...displayText,
    color: appInk,
    fontSize: 20,
    fontWeight: '900',
  },
  timelineRow: {
    position: 'relative',
    minHeight: 68,
    flexDirection: 'row',
    gap: 14,
  },
  timelineMarker: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  timelineLine: {
    position: 'absolute',
    left: 14,
    top: 30,
    width: 2,
    height: 38,
    backgroundColor: appBorder,
  },
  timelineText: {
    flex: 1,
    paddingTop: 1,
  },
  timelineDay: {
    ...roundedText,
    color: appMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  timelineLabel: {
    ...roundedText,
    color: appInk,
    fontSize: 14,
    fontWeight: '800',
    marginTop: 5,
  },
  planCard: {
    minHeight: 92,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appCard,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  planCardSelected: {
    borderColor: colors.primary,
    backgroundColor: appTint,
  },
  planMain: {
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: appBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  radioSelected: {
    borderColor: colors.primary,
  },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  planText: {
    flex: 1,
  },
  planName: {
    ...roundedText,
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
  },
  planPrice: {
    ...displayText,
    color: appInk,
    fontSize: 28,
    fontWeight: '900',
    marginTop: 6,
  },
  planDetail: {
    ...roundedText,
    color: appMuted,
    fontSize: 12,
    marginTop: 6,
    lineHeight: 17,
  },
  bestValue: {
    borderRadius: 8,
    backgroundColor: colors.successBg,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  bestValueText: {
    ...roundedText,
    color: appInk,
    fontSize: 10,
    fontWeight: '900',
  },
  termsBlock: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: colors.surfaceMuted,
    padding: 14,
    gap: 10,
  },
  purchaseError: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.warningBg,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  purchaseErrorText: {
    ...roundedText,
    color: colors.warning,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  restoreButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  termLine: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  termText: {
    ...roundedText,
    flex: 1,
    color: appMuted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  restoreText: {
    ...roundedText,
    color: appMuted,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '800',
  },
  chatBubble: {
    maxWidth: '84%',
    alignSelf: 'flex-start',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appCard,
    padding: 13,
  },
  chatBubbleOutgoing: {
    alignSelf: 'flex-end',
    backgroundColor: appInk,
    borderColor: appInk,
  },
  chatText: {
    ...roundedText,
    color: appInk,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  chatTextOutgoing: {
    color: colors.onPrimary,
  },
  secondaryAction: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appBorder,
    backgroundColor: appCard,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryActionText: {
    ...roundedText,
    color: appInk,
    fontSize: 14,
    fontWeight: '900',
  },
  agentStatus: {
    minHeight: 88,
    borderRadius: 8,
    backgroundColor: appCard,
    borderWidth: 1,
    borderColor: appBorder,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  agentTitle: {
    ...displayText,
    color: appInk,
    fontSize: 23,
    fontWeight: '900',
    marginTop: 6,
  },
  onPill: {
    borderRadius: 8,
    backgroundColor: colors.successBg,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  onPillText: {
    ...roundedText,
    color: appInk,
    fontSize: 12,
    fontWeight: '900',
  },
  statGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  metric: {
    flex: 1,
    minHeight: 92,
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    justifyContent: 'center',
  },
  metricValue: {
    ...displayText,
    fontSize: 31,
    fontWeight: '900',
  },
  metricLabel: {
    ...roundedText,
    color: appMuted,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 5,
  },
  footer: {
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: appPaper,
  },
  cta: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: colors.primaryActive,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  ctaDisabled: {
    opacity: 0.45,
  },
  ctaText: {
    ...roundedText,
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  pressed: {
    opacity: 0.85,
  },
});
