import { StyleSheet } from 'react-native';
import { colors } from '@/components/ui';

const lightBg = '#fbfbfd';
const lightBand = '#f4f1ff';
const lightCard = '#ffffff';
const lightBorder = '#d8d3ee';
const lightInk = '#161334';
const lightMuted = '#5f5a7d';
const lightFaint = '#837ca6';
const darkBg = '#0d0a26';
const darkText = '#f4f1ff';
const darkMuted = '#b8aee0';
const darkBorder = '#3d2f80';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: darkBg,
  },
  page: {
    backgroundColor: darkBg,
    paddingBottom: 160,
    gap: 16,
  },
  nav: {
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    zIndex: 2,
    backgroundColor: darkBg,
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    minWidth: 0,
  },
  brandText: {
    color: darkText,
    fontSize: 18,
    fontWeight: '800',
  },
  navActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  textButton: {
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  textButtonLabel: {
    color: darkMuted,
    fontWeight: '700',
  },
  smallButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  smallButtonLabel: {
    color: colors.onPrimary,
    fontWeight: '800',
  },
  heroWrap: {
    position: 'relative',
    overflow: 'hidden',
    width: '100%',
    backgroundColor: darkBg,
  },
  hero: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 40,
    zIndex: 1,
  },
  stackSection: {
    flexDirection: 'column',
  },
  heroCopy: {
    flex: 1,
    minWidth: 300,
    gap: 18,
  },
  heroMascot: {
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroMockup: {
    flex: 1,
    minWidth: 300,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  kicker: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: darkText,
    fontSize: 52,
    lineHeight: 58,
    fontWeight: '900',
    maxWidth: 650,
  },
  heroTitleMobile: {
    fontSize: 38,
    lineHeight: 44,
  },
  heroBody: {
    color: darkMuted,
    fontSize: 18,
    lineHeight: 28,
    maxWidth: 600,
  },
  ctaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  ctaColumn: {
    alignItems: 'stretch',
  },
  primaryButton: {
    minHeight: 48,
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: colors.primaryActive,
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  primaryButtonLabel: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    minHeight: 48,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: darkBorder,
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryButtonLabel: {
    color: darkText,
    fontSize: 15,
    fontWeight: '900',
  },
  preview: {
    flex: 1,
    minWidth: 300,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 18,
    gap: 14,
  },
  previewTopbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  previewLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  previewTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 3,
  },
  statusPill: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  statusPillText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '900',
  },
  messageCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 8,
    padding: 14,
    gap: 2,
  },
  agentCard: {
    backgroundColor: lightBand,
    borderColor: lightBorder,
    borderWidth: 1,
  },
  messageName: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  messageText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
  },
  previewGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  metric: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
  },
  metricValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  metricLabel: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 3,
  },
  band: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 54,
    gap: 22,
    backgroundColor: lightBg,
    borderRadius: 8,
  },
  bandAlt: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    backgroundColor: lightBand,
    paddingHorizontal: 24,
    paddingVertical: 56,
    gap: 24,
    borderRadius: 8,
  },
  bandDark: {
    width: '100%',
    backgroundColor: darkBg,
    paddingHorizontal: 24,
    paddingVertical: 60,
    gap: 24,
  },
  sectionIntro: {
    maxWidth: 740,
    alignSelf: 'center',
    alignItems: 'center',
    gap: 10,
  },
  sectionTitle: {
    color: lightInk,
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '900',
    textAlign: 'center',
  },
  sectionTitleSmall: {
    color: lightInk,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
  },
  sectionBody: {
    color: lightMuted,
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  darkKicker: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  darkSectionTitle: {
    color: darkText,
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '900',
    textAlign: 'center',
  },
  darkSectionBody: {
    color: darkMuted,
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  roleGrid: {
    maxWidth: 980,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 16,
    width: '100%',
  },
  rolePanel: {
    flex: 1,
    minWidth: 280,
    backgroundColor: lightCard,
    borderWidth: 1,
    borderColor: lightBorder,
    borderRadius: 8,
    padding: 20,
    gap: 12,
  },
  pressed: {
    opacity: 0.84,
  },
  iconShell: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: lightBand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    color: lightInk,
    fontSize: 20,
    fontWeight: '900',
  },
  cardBody: {
    color: lightMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  inlineAction: {
    color: colors.primaryActive,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 4,
  },
  threeGrid: {
    width: '100%',
    maxWidth: 1040,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  featureCard: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1,
    borderColor: lightBorder,
    borderRadius: 8,
    padding: 18,
    gap: 10,
    backgroundColor: lightCard,
  },
  splitBand: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 54,
    flexDirection: 'row',
    gap: 16,
    backgroundColor: lightBg,
    borderRadius: 8,
  },
  checklist: {
    flex: 1,
    minWidth: 280,
    backgroundColor: lightCard,
    borderColor: lightBorder,
    borderWidth: 1,
    borderRadius: 8,
    padding: 22,
    gap: 14,
  },
  checklistWarm: {
    backgroundColor: lightBand,
    borderColor: lightBorder,
  },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  checkDot: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkText: {
    flex: 1,
    color: lightInk,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  trustGrid: {
    width: '100%',
    maxWidth: 1040,
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  trustItem: {
    flex: 1,
    minWidth: 220,
    backgroundColor: lightCard,
    borderColor: lightBorder,
    borderWidth: 1,
    borderRadius: 8,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  trustText: {
    flex: 1,
    color: lightInk,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  launchBand: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 56,
    flexDirection: 'row',
    gap: 24,
    alignItems: 'center',
    backgroundColor: lightBg,
    borderRadius: 8,
  },
  launchCopy: {
    flex: 1,
    gap: 10,
  },
  priceBox: {
    flex: 1,
    minWidth: 280,
    backgroundColor: lightCard,
    borderWidth: 1,
    borderColor: lightBorder,
    borderRadius: 8,
    padding: 22,
    gap: 8,
  },
  priceLabel: {
    color: colors.primaryActive,
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  priceValue: {
    color: lightInk,
    fontSize: 30,
    fontWeight: '900',
  },
  priceBody: {
    color: lightMuted,
    fontSize: 15,
    lineHeight: 23,
  },
  faqList: {
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
    gap: 12,
  },
  faqItem: {
    borderColor: lightBorder,
    borderWidth: 1,
    borderRadius: 8,
    padding: 18,
    backgroundColor: lightCard,
    gap: 6,
  },
  faqQuestion: {
    color: lightInk,
    fontSize: 17,
    fontWeight: '900',
  },
  faqAnswer: {
    color: lightMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  finalCta: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 64,
    paddingBottom: 86,
    gap: 18,
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: darkBg,
  },
  footerPanel: {
    borderWidth: 1,
    borderColor: lightBorder,
    borderRadius: 8,
    backgroundColor: lightCard,
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 28,
  },
  footerPanelMobile: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  footerBrandBlock: {
    flex: 1,
    gap: 12,
  },
  footerBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  footerOwl: {
    width: 34,
    height: 34,
  },
  footerBrandText: {
    color: lightInk,
    fontSize: 18,
    fontWeight: '900',
  },
  footerBody: {
    color: lightMuted,
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 520,
  },
  footerCtaBlock: {
    flex: 1,
    alignItems: 'flex-end',
    gap: 14,
  },
  footerCtaBlockMobile: {
    alignItems: 'stretch',
  },
  finalTitle: {
    color: lightInk,
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '900',
    textAlign: 'right',
    maxWidth: 460,
  },
  footerTitleMobile: {
    textAlign: 'left',
  },
  footerMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 4,
  },
  footerMetaMobile: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  footerMetaText: {
    color: lightFaint,
    fontSize: 12,
    fontWeight: '800',
  },
  footerLinks: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  footerLink: {
    color: colors.primaryActive,
    fontSize: 12,
    fontWeight: '900',
  },
  cookieBanner: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 18,
    alignSelf: 'center',
    backgroundColor: lightCard,
    borderColor: lightBorder,
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  cookieBannerMobile: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  cookieText: {
    flex: 1,
    color: lightMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  cookieActions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  cookieGhost: {
    borderWidth: 1,
    borderColor: lightBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  cookieGhostLabel: {
    color: lightInk,
    fontSize: 13,
    fontWeight: '800',
  },
  cookieAccept: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  cookieAcceptLabel: {
    color: colors.onPrimary,
    fontSize: 13,
    fontWeight: '900',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(13, 10, 38, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  modalCard: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '92%',
    backgroundColor: lightCard,
    borderColor: lightBorder,
    borderWidth: 1,
    borderRadius: 8,
    padding: 20,
    gap: 16,
  },
  modalCardMobile: {
    padding: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalTitle: {
    color: lightInk,
    fontSize: 24,
    fontWeight: '900',
  },
  modalIntro: {
    color: lightMuted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    maxWidth: 420,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: lightBand,
  },
  segmented: {
    backgroundColor: lightBand,
    borderRadius: 8,
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  segment: {
    flex: 1,
    borderRadius: 7,
    paddingVertical: 10,
    alignItems: 'center',
  },
  segmentActive: {
    backgroundColor: colors.primary,
  },
  segmentText: {
    color: lightMuted,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: colors.onPrimary,
  },
  form: {
    gap: 12,
  },
  inputGroup: {
    gap: 6,
  },
  inputLabel: {
    color: lightInk,
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: lightBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: lightInk,
    fontSize: 15,
    backgroundColor: lightBg,
  },
  modalAction: {
    minHeight: 48,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 4,
    shadowColor: colors.primaryActive,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  modalActionLabel: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.6,
  },
  successBox: {
    backgroundColor: lightBand,
    borderColor: lightBorder,
    borderWidth: 1,
    borderRadius: 8,
    padding: 18,
    alignItems: 'center',
    gap: 8,
  },
  successTitle: {
    color: lightInk,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  successText: {
    color: lightMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  fieldError: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  inputError: {
    borderColor: colors.danger,
  },
  submitError: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  exampleTag: {
    alignSelf: 'flex-start',
    backgroundColor: lightBand,
    borderColor: lightBorder,
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    color: lightFaint,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    overflow: 'hidden',
  },
  owlBust: {
    width: 36,
    height: 36,
  },
});
