import { Platform, StyleSheet } from 'react-native';
import { colors } from '@/components/ui';

export const landingPalette = {
  ink: '#09080d',
  inkRaised: '#121018',
  inkSoft: '#1b1721',
  paper: '#f6f0e6',
  paperSoft: '#eee6d8',
  muted: '#b9b3d6',
  darkText: colors.text,
  bodyText: colors.textSecondary,
  textMuted: colors.textMuted,
  purple: '#7460d6',
  purpleActive: '#5f4cbd',
  purpleAccent: '#8b76e6',
  purpleDim: '#d7cdea',
  borderDark: 'rgba(116, 96, 214, 0.24)',
  borderDarkSubtle: 'rgba(116, 96, 214, 0.15)',
  shadow: 'rgba(0, 0, 0, 0.22)',
  onPurple: colors.onPrimary,
  danger: colors.danger,
};

export const landingFonts = {
  display: Platform.select({
    web: 'Georgia, "Times New Roman", serif',
    default: 'serif',
  }),
  rounded: Platform.select({
    web: 'ui-rounded, "SF Pro Rounded", "Avenir Next Rounded", "Nunito", system-ui, sans-serif',
    default: undefined,
  }),
};

const roundedText = {
  fontFamily: landingFonts.rounded,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: landingPalette.ink,
  },
  page: {
    backgroundColor: landingPalette.ink,
    paddingBottom: 120,
  },
  nav: {
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    zIndex: 2,
    backgroundColor: landingPalette.ink,
    borderBottomWidth: 1,
    borderBottomColor: landingPalette.borderDarkSubtle,
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    minWidth: 0,
  },
  owlBust: {
    width: 34,
    height: 34,
  },
  brandText: {
    ...roundedText,
    color: landingPalette.paper,
    fontSize: 18,
    fontWeight: '900',
  },
  navActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  textButton: {
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  textButtonLabel: {
    ...roundedText,
    color: landingPalette.muted,
    fontWeight: '800',
  },
  smallButton: {
    backgroundColor: landingPalette.purple,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: landingPalette.purpleActive,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
  },
  smallButtonLabel: {
    ...roundedText,
    color: landingPalette.paper,
    fontWeight: '900',
  },
  heroWrap: {
    position: 'relative',
    overflow: 'hidden',
    width: '100%',
    backgroundColor: landingPalette.ink,
  },
  hero: {
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 72,
    paddingBottom: 84,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 44,
    zIndex: 1,
  },
  heroMobile: {
    paddingTop: 44,
    paddingBottom: 50,
    gap: 30,
    alignItems: 'stretch',
  },
  stackSection: {
    flexDirection: 'column',
  },
  heroCopy: {
    flex: 1,
    minWidth: 300,
    gap: 20,
  },
  heroMockup: {
    flex: 1,
    minWidth: 300,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  heroMockupMobile: {
    paddingTop: 12,
    paddingBottom: 0,
  },
  kicker: {
    ...roundedText,
    color: landingPalette.purpleAccent,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: landingPalette.paper,
    fontFamily: landingFonts.display,
    fontSize: 55,
    lineHeight: 61,
    fontWeight: '900',
    maxWidth: 650,
  },
  heroTitleMobile: {
    fontSize: 38,
    lineHeight: 44,
  },
  heroBody: {
    ...roundedText,
    color: landingPalette.muted,
    fontSize: 18,
    lineHeight: 29,
    maxWidth: 610,
  },
  heroLogoMention: {
    ...roundedText,
    color: landingPalette.paper,
    fontWeight: '900',
  },
  ctaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    flexWrap: 'wrap',
    marginTop: 2,
  },
  ctaColumn: {
    alignItems: 'stretch',
  },
  primaryButton: {
    minHeight: 50,
    backgroundColor: landingPalette.purple,
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: landingPalette.purpleActive,
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  primaryButtonLabel: {
    ...roundedText,
    color: landingPalette.onPurple,
    fontSize: 15,
    fontWeight: '900',
  },
  storyBand: {
    width: '100%',
    backgroundColor: landingPalette.paper,
    paddingHorizontal: 24,
    paddingVertical: 78,
  },
  storyLayout: {
    width: '100%',
    maxWidth: 1120,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 58,
    alignItems: 'flex-start',
  },
  storyIntro: {
    flex: 0.9,
    minWidth: 280,
    gap: 13,
  },
  storyTitle: {
    color: landingPalette.darkText,
    fontFamily: landingFonts.display,
    fontSize: 38,
    lineHeight: 45,
    fontWeight: '900',
    maxWidth: 520,
  },
  storyTitleMobile: {
    fontSize: 31,
    lineHeight: 38,
  },
  storyBody: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 16,
    lineHeight: 25,
    maxWidth: 500,
  },
  clientTextAction: {
    alignSelf: 'flex-start',
    paddingTop: 8,
    paddingBottom: 4,
  },
  clientTextActionLabel: {
    ...roundedText,
    color: landingPalette.purpleActive,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '900',
  },
  storySteps: {
    flex: 1.1,
    minWidth: 300,
    gap: 0,
    borderTopWidth: 1,
    borderTopColor: landingPalette.purpleDim,
  },
  storyStep: {
    flexDirection: 'row',
    gap: 18,
    paddingVertical: 22,
    borderBottomWidth: 1,
    borderBottomColor: landingPalette.purpleDim,
  },
  storyStepNumber: {
    width: 34,
    ...roundedText,
    color: landingPalette.purpleActive,
    fontSize: 13,
    lineHeight: 22,
    fontWeight: '900',
  },
  storyStepCopy: {
    flex: 1,
    gap: 6,
  },
  storyStepTitle: {
    ...roundedText,
    color: landingPalette.darkText,
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '900',
  },
  storyStepBody: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 15,
    lineHeight: 24,
  },
  band: {
    width: '100%',
    backgroundColor: landingPalette.paper,
    paddingHorizontal: 24,
    paddingVertical: 62,
    gap: 26,
  },
  bandAlt: {
    width: '100%',
    backgroundColor: landingPalette.paperSoft,
    paddingHorizontal: 24,
    paddingVertical: 64,
    gap: 26,
  },
  bandDark: {
    width: '100%',
    backgroundColor: landingPalette.inkRaised,
    paddingHorizontal: 24,
    paddingVertical: 66,
    gap: 28,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: landingPalette.borderDark,
  },
  sectionIntro: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    alignItems: 'center',
    gap: 11,
  },
  sectionTitle: {
    fontFamily: landingFonts.display,
    color: landingPalette.darkText,
    fontSize: 34,
    lineHeight: 41,
    fontWeight: '900',
    textAlign: 'center',
  },
  sectionTitleSmall: {
    fontFamily: landingFonts.display,
    color: landingPalette.darkText,
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '900',
  },
  sectionBody: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 16,
    lineHeight: 25,
    textAlign: 'center',
  },
  darkKicker: {
    ...roundedText,
    color: landingPalette.purpleAccent,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  darkSectionTitle: {
    fontFamily: landingFonts.display,
    color: landingPalette.paper,
    fontSize: 34,
    lineHeight: 41,
    fontWeight: '900',
    textAlign: 'center',
  },
  darkSectionBody: {
    ...roundedText,
    color: landingPalette.muted,
    fontSize: 16,
    lineHeight: 25,
    textAlign: 'center',
  },
  roleGrid: {
    maxWidth: 1040,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 16,
    width: '100%',
  },
  rolePanel: {
    flex: 1,
    minWidth: 280,
    backgroundColor: landingPalette.paper,
    borderWidth: 1,
    borderColor: landingPalette.purpleDim,
    borderRadius: 8,
    padding: 22,
    gap: 12,
    shadowColor: landingPalette.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 1,
  },
  pressed: {
    opacity: 0.84,
  },
  iconShell: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: landingPalette.darkText,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    ...roundedText,
    color: landingPalette.darkText,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '900',
  },
  cardBody: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 15,
    lineHeight: 23,
  },
  inlineAction: {
    ...roundedText,
    color: landingPalette.purpleActive,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 4,
  },
  threeGrid: {
    width: '100%',
    maxWidth: 1080,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  featureCard: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1,
    borderColor: landingPalette.purpleDim,
    borderRadius: 8,
    padding: 20,
    gap: 11,
    backgroundColor: landingPalette.paper,
  },
  featureIcon: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: landingPalette.darkText,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splitBand: {
    width: '100%',
    backgroundColor: landingPalette.paper,
    paddingHorizontal: 24,
    paddingVertical: 62,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
  },
  checklist: {
    flex: 1,
    maxWidth: 530,
    minWidth: 280,
    backgroundColor: landingPalette.paper,
    borderColor: landingPalette.purpleDim,
    borderWidth: 1,
    borderRadius: 8,
    padding: 24,
    gap: 14,
  },
  checklistWarm: {
    backgroundColor: landingPalette.paperSoft,
    borderColor: landingPalette.purpleDim,
  },
  checkIntro: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 14.5,
    lineHeight: 22,
    marginBottom: 2,
  },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  checkDot: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: landingPalette.purple,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  checkText: {
    flex: 1,
    ...roundedText,
    color: landingPalette.darkText,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  trustGrid: {
    width: '100%',
    maxWidth: 1080,
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  trustItem: {
    flex: 1,
    minWidth: 230,
    backgroundColor: landingPalette.inkSoft,
    borderColor: landingPalette.borderDark,
    borderWidth: 1,
    borderRadius: 8,
    padding: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  trustText: {
    flex: 1,
    ...roundedText,
    color: landingPalette.paper,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  launchBand: {
    width: '100%',
    backgroundColor: landingPalette.paper,
    paddingHorizontal: 24,
    paddingVertical: 64,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 28,
    alignItems: 'center',
  },
  launchCopy: {
    flex: 1,
    maxWidth: 560,
    gap: 10,
  },
  priceBox: {
    flex: 1,
    maxWidth: 460,
    minWidth: 280,
    backgroundColor: landingPalette.darkText,
    borderWidth: 1,
    borderColor: landingPalette.borderDark,
    borderRadius: 8,
    padding: 24,
    gap: 9,
  },
  priceLabel: {
    ...roundedText,
    color: landingPalette.purpleAccent,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  priceValue: {
    fontFamily: landingFonts.display,
    color: landingPalette.paper,
    fontSize: 29,
    lineHeight: 35,
    fontWeight: '900',
  },
  priceBody: {
    ...roundedText,
    color: landingPalette.muted,
    fontSize: 15,
    lineHeight: 23,
  },
  faqList: {
    width: '100%',
    maxWidth: 920,
    alignSelf: 'center',
    gap: 12,
  },
  faqItem: {
    borderColor: landingPalette.purpleDim,
    borderWidth: 1,
    borderRadius: 8,
    padding: 19,
    backgroundColor: landingPalette.paper,
    gap: 7,
  },
  faqQuestion: {
    ...roundedText,
    color: landingPalette.darkText,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '900',
  },
  faqAnswer: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 15,
    lineHeight: 23,
  },
  finalCta: {
    width: '100%',
    paddingHorizontal: 24,
    paddingTop: 70,
    paddingBottom: 82,
    gap: 18,
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: landingPalette.ink,
  },
  footerPanel: {
    width: '100%',
    maxWidth: 1120,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: landingPalette.borderDark,
    borderRadius: 8,
    backgroundColor: 'rgba(18, 16, 24, 0.94)',
    padding: 26,
    gap: 28,
    zIndex: 1,
  },
  footerPanelMobile: {
    padding: 22,
  },
  footerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 30,
  },
  footerTopMobile: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  footerBrandBlock: {
    flex: 1,
    gap: 12,
  },
  footerBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  footerOwl: {
    width: 32,
    height: 32,
  },
  footerBrandText: {
    ...roundedText,
    color: landingPalette.paper,
    fontSize: 18,
    fontWeight: '900',
  },
  footerBody: {
    ...roundedText,
    color: landingPalette.muted,
    fontSize: 15,
    lineHeight: 23,
    maxWidth: 520,
  },
  footerCtaBlock: {
    flex: 1,
    alignItems: 'flex-end',
    gap: 14,
  },
  footerCtaBlockMobile: {
    alignItems: 'stretch',
  },
  finalTitle: {
    color: landingPalette.paper,
    fontFamily: landingFonts.display,
    fontSize: 27,
    lineHeight: 34,
    fontWeight: '900',
    textAlign: 'right',
    maxWidth: 480,
  },
  footerTitleMobile: {
    textAlign: 'left',
  },
  footerColumns: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: landingPalette.borderDark,
    paddingTop: 22,
    gap: 18,
  },
  footerColumnsMobile: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 20,
  },
  footerColumn: {
    width: 210,
    maxWidth: '32%',
    gap: 10,
  },
  footerColumnMobile: {
    width: '100%',
    maxWidth: '100%',
  },
  footerColumnTitle: {
    ...roundedText,
    color: landingPalette.paper,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  footerColumnLinks: {
    gap: 9,
  },
  footerMetaText: {
    width: '100%',
    maxWidth: 1120,
    alignSelf: 'center',
    ...roundedText,
    color: landingPalette.muted,
    fontSize: 12,
    fontWeight: '800',
    zIndex: 1,
  },
  footerLink: {
    ...roundedText,
    color: landingPalette.purpleAccent,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '900',
  },
  cookieBanner: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 18,
    alignSelf: 'center',
    backgroundColor: landingPalette.paper,
    borderColor: landingPalette.purpleDim,
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    shadowColor: landingPalette.shadow,
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  cookieBannerMobile: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  cookieText: {
    flex: 1,
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 13,
    lineHeight: 19,
  },
  cookieActions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  cookieGhost: {
    borderWidth: 1,
    borderColor: landingPalette.purpleDim,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  cookieGhostLabel: {
    ...roundedText,
    color: landingPalette.darkText,
    fontSize: 13,
    fontWeight: '800',
  },
  cookieAccept: {
    backgroundColor: landingPalette.purple,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  cookieAcceptLabel: {
    ...roundedText,
    color: landingPalette.onPurple,
    fontSize: 13,
    fontWeight: '900',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(9, 8, 13, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  modalCard: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '92%',
    backgroundColor: landingPalette.paper,
    borderColor: landingPalette.purpleDim,
    borderWidth: 1,
    borderRadius: 8,
    padding: 20,
    gap: 16,
  },
  modalCardMobile: {
    padding: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  modalTitle: {
    fontFamily: landingFonts.display,
    color: landingPalette.darkText,
    fontSize: 24,
    fontWeight: '900',
  },
  modalIntro: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    maxWidth: 420,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: landingPalette.paperSoft,
  },
  segmented: {
    backgroundColor: landingPalette.paperSoft,
    borderRadius: 8,
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  segment: {
    flex: 1,
    borderRadius: 7,
    paddingVertical: 10,
    alignItems: 'center',
  },
  segmentActive: {
    backgroundColor: landingPalette.purple,
  },
  segmentText: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: landingPalette.onPurple,
  },
  form: {
    gap: 12,
  },
  googleAuthButton: {
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: landingPalette.inkRaised,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  googleAuthIcon: {
    width: 22,
    height: 22,
    borderRadius: 4,
    ...roundedText,
    backgroundColor: landingPalette.paper,
    color: landingPalette.inkRaised,
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 22,
    textAlign: 'center',
    overflow: 'hidden',
  },
  googleAuthLabel: {
    ...roundedText,
    color: landingPalette.paper,
    fontSize: 15,
    fontWeight: '900',
  },
  appleAuthButton: {
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: landingPalette.paper,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 10,
  },
  appleAuthIcon: {
    ...roundedText,
    color: landingPalette.ink,
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
  },
  appleAuthLabel: {
    ...roundedText,
    color: landingPalette.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  authDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginVertical: 2,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: landingPalette.purpleDim,
  },
  authDividerText: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  inputGroup: {
    gap: 6,
  },
  inputLabel: {
    ...roundedText,
    color: landingPalette.darkText,
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: landingPalette.purpleDim,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...roundedText,
    color: landingPalette.darkText,
    fontSize: 15,
    backgroundColor: landingPalette.paper,
  },
  modalAction: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: landingPalette.purple,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 4,
    shadowColor: landingPalette.purpleActive,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  modalActionLabel: {
    ...roundedText,
    color: landingPalette.onPurple,
    fontSize: 15,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.6,
  },
  successBox: {
    backgroundColor: landingPalette.paperSoft,
    borderColor: landingPalette.purpleDim,
    borderWidth: 1,
    borderRadius: 8,
    padding: 18,
    alignItems: 'center',
    gap: 8,
  },
  successTitle: {
    ...roundedText,
    color: landingPalette.darkText,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  successText: {
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  fieldError: {
    ...roundedText,
    color: landingPalette.danger,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  inputError: {
    borderColor: landingPalette.danger,
  },
  submitError: {
    ...roundedText,
    color: landingPalette.danger,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  exampleTag: {
    alignSelf: 'flex-start',
    backgroundColor: landingPalette.paperSoft,
    borderColor: landingPalette.purpleDim,
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    ...roundedText,
    color: landingPalette.bodyText,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    overflow: 'hidden',
  },
});
