import { StyleSheet } from 'react-native';
import { colors } from '@/components/ui';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  page: {
    paddingBottom: 160,
  },
  nav: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    zIndex: 2,
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  brandText: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  navActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  textButton: {
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  textButtonLabel: {
    color: colors.textSecondary,
    fontWeight: '700',
  },
  smallButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  smallButtonLabel: {
    color: colors.onPrimary,
    fontWeight: '800',
  },
  heroWrap: {
    position: 'relative',
    overflow: 'hidden',
    width: '100%',
  },
  hero: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 40,
    zIndex: 1,
  },
  stackSection: {
    flexDirection: 'column',
  },
  heroCopy: {
    flex: 1,
    minWidth: 300,
    gap: 18,
  },
  heroMascot: {
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroMockup: {
    flex: 1,
    minWidth: 300,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  kicker: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: colors.text,
    fontSize: 52,
    lineHeight: 58,
    fontWeight: '900',
    maxWidth: 650,
  },
  heroTitleMobile: {
    fontSize: 38,
    lineHeight: 44,
  },
  heroBody: {
    color: colors.textSecondary,
    fontSize: 18,
    lineHeight: 28,
    maxWidth: 600,
  },
  ctaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  ctaColumn: {
    alignItems: 'stretch',
  },
  primaryButton: {
    minHeight: 48,
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonLabel: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    minHeight: 48,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryButtonLabel: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  preview: {
    flex: 1,
    minWidth: 300,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 18,
    gap: 14,
  },
  previewTopbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  previewLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  previewTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 3,
  },
  statusPill: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  statusPillText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '900',
  },
  messageCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 8,
    padding: 14,
    gap: 5,
  },
  agentCard: {
    backgroundColor: colors.background,
    borderColor: colors.borderStrong,
    borderWidth: 1,
  },
  messageName: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  messageText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
  },
  previewGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  metric: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
  },
  metricValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  metricLabel: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 3,
  },
  band: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 54,
    gap: 22,
  },
  bandAlt: {
    width: '100%',
    backgroundColor: colors.surface,
    paddingHorizontal: 24,
    paddingVertical: 56,
    gap: 24,
  },
  sectionIntro: {
    maxWidth: 740,
    alignSelf: 'center',
    alignItems: 'center',
    gap: 10,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '900',
    textAlign: 'center',
  },
  sectionTitleSmall: {
    color: colors.text,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
  },
  sectionBody: {
    color: colors.textSecondary,
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  roleGrid: {
    maxWidth: 980,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 16,
    width: '100%',
  },
  rolePanel: {
    flex: 1,
    minWidth: 280,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 20,
    gap: 12,
  },
  pressed: {
    opacity: 0.84,
  },
  iconShell: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  cardBody: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  inlineAction: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 4,
  },
  threeGrid: {
    width: '100%',
    maxWidth: 1040,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  featureCard: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 18,
    gap: 10,
    backgroundColor: colors.surface,
  },
  splitBand: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 54,
    flexDirection: 'row',
    gap: 16,
  },
  checklist: {
    flex: 1,
    minWidth: 280,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderWidth: 1,
    borderRadius: 8,
    padding: 22,
    gap: 14,
  },
  checklistWarm: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
  },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  checkDot: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkText: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  trustGrid: {
    width: '100%',
    maxWidth: 1040,
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  trustItem: {
    flex: 1,
    minWidth: 220,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  trustText: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  launchBand: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 56,
    flexDirection: 'row',
    gap: 24,
    alignItems: 'center',
  },
  launchCopy: {
    flex: 1,
    gap: 10,
  },
  priceBox: {
    flex: 1,
    minWidth: 280,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 8,
    padding: 22,
    gap: 8,
  },
  priceLabel: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  priceValue: {
    color: colors.text,
    fontSize: 30,
    fontWeight: '900',
  },
  priceBody: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 23,
  },
  faqList: {
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
    gap: 12,
  },
  faqItem: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 18,
    backgroundColor: colors.surface,
    gap: 6,
  },
  faqQuestion: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
  },
  faqAnswer: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  finalCta: {
    width: '100%',
    maxWidth: 980,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 80,
    alignItems: 'center',
    gap: 18,
    position: 'relative',
    overflow: 'hidden',
  },
  finalTitle: {
    color: colors.text,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '900',
    textAlign: 'center',
  },
  cookieBanner: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 18,
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.borderStrong,
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  cookieBannerMobile: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  cookieText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  cookieActions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  cookieGhost: {
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  cookieGhostLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  cookieAccept: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  cookieAcceptLabel: {
    color: colors.onPrimary,
    fontSize: 13,
    fontWeight: '900',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(13, 10, 38, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  modalCard: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '92%',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 20,
    gap: 16,
  },
  modalCardMobile: {
    padding: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
  },
  modalIntro: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    maxWidth: 420,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  segmented: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 8,
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  segment: {
    flex: 1,
    borderRadius: 7,
    paddingVertical: 10,
    alignItems: 'center',
  },
  segmentActive: {
    backgroundColor: colors.primary,
  },
  segmentText: {
    color: colors.textSecondary,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: colors.onPrimary,
  },
  form: {
    gap: 12,
  },
  inputGroup: {
    gap: 6,
  },
  inputLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    fontSize: 15,
    backgroundColor: colors.background,
  },
  modalAction: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 4,
  },
  modalActionLabel: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.6,
  },
  successBox: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderWidth: 1,
    borderRadius: 8,
    padding: 18,
    alignItems: 'center',
    gap: 8,
  },
  successTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  successText: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  fieldError: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  inputError: {
    borderColor: colors.danger,
  },
  submitError: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  exampleTag: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderStrong,
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    overflow: 'hidden',
  },
  owlBust: {
    width: 36,
    height: 36,
  },
});
